variable project {}
variable region {}
variable zone {}
variable public_key_path {}
variable private_key_path {}
variable public_key_centr {}
variable public_key_Centr {}
variable app_disk_image {}
variable db_disk_image {}
