---
- name: Install MongoDB 4.2
  hosts: all
  become: true
  tasks:

  -  name: convert gpg
     shell: "{{ item }}"
     with_items:
       - gpg --keyserver hkp://keys.gnupg.net --recv-keys 4B7C549A058F8B6B
       - gpg -a --export 4B7C549A058F8B6B | sudo apt-key add -

  # Подключаем репозиторий с пакетами mongodb
  - name: Add APT repository
    apt_repository:
      update_cache: yes
      repo: deb [ arch=amd64,arm64 ] https://repo.mongodb.org/apt/ubuntu xenial/mongodb-org/4.2 multiverse
     # repo: deb [ arch=amd64,arm64 ] http://repo.mongodb.org/apt/ubuntu xenial/mongodb-org/3.2 multiverse
      state: present

  # Выполним установку пакета
  - name: Install mongodb package
    apt:
      name: mongodb-org
      state: present

  # Включаем сервис
  - name: Configure service supervisor
    systemd:
      name: mongod
      state: started
      enabled: yes
